server:
  port: 8081
  servlet:
    context-path: /admin
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mariadb://localhost:3306/bookstore
    username: root
    password: 2001

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect